'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=GRNSDNOFFICE-PC\SQLEXPRESS;Initial Catalog=RetrieveSecurity;Integrate"& _ 
            "d Security=True")>  _
        Public ReadOnly Property SecurityConnectionStr() As String
            Get
                Return CType(Me("SecurityConnectionStr"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=GRNSDNOFFICE-PC\SQLEXPRESS;Initial Catalog=TellersAssistant2008;Integ"& _ 
            "rated Security=True")>  _
        Public ReadOnly Property TellersAssistant2008ConnectionString() As String
            Get
                Return CType(Me("TellersAssistant2008ConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ctRS232")>  _
        Public Property ImageTransferMethod() As String
            Get
                Return CType(Me("ImageTransferMethod"),String)
            End Get
            Set
                Me("ImageTransferMethod") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("300")>  _
        Public Property ImageTransferDelayRS232() As Integer
            Get
                Return CType(Me("ImageTransferDelayRS232"),Integer)
            End Get
            Set
                Me("ImageTransferDelayRS232") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1000")>  _
        Public Property ImageTransferDelayFTP() As Integer
            Get
                Return CType(Me("ImageTransferDelayFTP"),Integer)
            End Get
            Set
                Me("ImageTransferDelayFTP") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ManualCheck200dpi.tif")>  _
        Public Property ManualCheckName() As String
            Get
                Return CType(Me("ManualCheckName"),String)
            End Get
            Set
                Me("ManualCheckName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("CheckImages")>  _
        Public Property DefaultImageFolder() As String
            Get
                Return CType(Me("DefaultImageFolder"),String)
            End Get
            Set
                Me("DefaultImageFolder") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("COM3")>  _
        Public Property PortSettingPortName() As String
            Get
                Return CType(Me("PortSettingPortName"),String)
            End Get
            Set
                Me("PortSettingPortName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("115200")>  _
        Public Property PortSettingBaudRate() As Integer
            Get
                Return CType(Me("PortSettingBaudRate"),Integer)
            End Get
            Set
                Me("PortSettingBaudRate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("None")>  _
        Public Property PortSettingParity() As String
            Get
                Return CType(Me("PortSettingParity"),String)
            End Get
            Set
                Me("PortSettingParity") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("8")>  _
        Public Property PortSettingDataBits() As Integer
            Get
                Return CType(Me("PortSettingDataBits"),Integer)
            End Get
            Set
                Me("PortSettingDataBits") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property PortSettingStopBits() As Integer
            Get
                Return CType(Me("PortSettingStopBits"),Integer)
            End Get
            Set
                Me("PortSettingStopBits") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("192.168.2.104")>  _
        Public Property ScannerIP() As String
            Get
                Return CType(Me("ScannerIP"),String)
            End Get
            Set
                Me("ScannerIP") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property InitializeScannerSettingsAtStartup() As Boolean
            Get
                Return CType(Me("InitializeScannerSettingsAtStartup"),Boolean)
            End Get
            Set
                Me("InitializeScannerSettingsAtStartup") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property LogScannerCmds() As Boolean
            Get
                Return CType(Me("LogScannerCmds"),Boolean)
            End Get
            Set
                Me("LogScannerCmds") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property LoggingTurnedOn() As Boolean
            Get
                Return CType(Me("LoggingTurnedOn"),Boolean)
            End Get
            Set
                Me("LoggingTurnedOn") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("MyTellerAssistant.xml")>  _
        Public Property MySettingsFilename() As String
            Get
                Return CType(Me("MySettingsFilename"),String)
            End Get
            Set
                Me("MySettingsFilename") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=GRNSDNOFFICE-PC\SQLEXPRESS;Initial Catalog=TellersAssistant2008;Integ"& _ 
            "rated Security=True")>  _
        Public ReadOnly Property ConnectionString() As String
            Get
                Return CType(Me("ConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=GRNSDNOFFICE-PC\SQLEXPRESS;Initial Catalog=TellersAssistant2008;Integ"& _ 
            "rated Security=True")>  _
        Public ReadOnly Property TellersAssistant2008ConnectionString1() As String
            Get
                Return CType(Me("TellersAssistant2008ConnectionString1"),String)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.TellerAssistant2012.My.MySettings
            Get
                Return Global.TellerAssistant2012.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
